name: Deploy
on:
  push:
    branches: ["main"]

jobs:
  build-and-push-to-ecr:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-aws-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to AWS ECR
        env:
          ECR_REGISTRY: ${{ steps.login-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
          IMAGE_TAG: latest-ns
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest
    needs: build-and-push-to-ecr
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-aws-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Print Environment Variables
        run: |
          echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
          echo "ECR_REGISTRY: ${{ steps.login-aws-ecr.outputs.registry }}"
          echo "AWS_ECR_REPO: ${{ secrets.AWS_ECR_REPO }}"

      - name: Deploy to EC2 Instance
        run: |
          command_id=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=i-007857caf670a98ac" \
            --comment "Pull Docker image and run it" \
            --parameters '{"commands": [
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.login-aws-ecr.outputs.registry }}",
              "docker pull ${{ steps.login-aws-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO }}:latest-ns",
              "docker run -p 3000:3000 --name api ${{ steps.login-aws-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO }}:latest-ns"
            ], "executionTimeout":["3600"]}' --query "Command.CommandId" --output text)

          echo "Command ID: $command_id"

          aws ssm wait command-executed \
            --command-id $command_id \
            --instance-id i-007857caf670a98ac || true 

          status=$(aws ssm list-commands --command-id $command_id --query "Commands[0].StatusDetails" --output text)

          echo "Status: $status"

          if [ "$status" == "Success" ]; then 
            echo "Command executed successfully"
          else
            echo "Command failed, time to get debugging information"
            aws ssm list-command-invocations --command-id $command_id --details
            exit 1
          fi
